# Generated by Django 5.2.16 on 2026-07-09 08:05

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "aa_discord_announcements",
            "0005_alter_pingtarget_restricted_to_group_and_more",
        ),
        ("groupmanagement", "0021_alter_authgroup_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pingtarget",
            name="name",
            field=models.OneToOneField(
                help_text="Name of the Discord role to ping. (Note: This must be an Auth group that is synced to Discord.)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discord_announcement_pingtarget",
                to="groupmanagement.group",
                verbose_name="Group name",
            ),
        ),
        migrations.AlterField(
            model_name="pingtarget",
            name="restricted_to_group",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict ping rights to the following groups…",
                related_name="discord_announcement_pingtarget_required_groups",
                to="groupmanagement.group",
                verbose_name="Group restrictions",
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="restricted_to_group",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrict ping rights to the following groups…",
                related_name="discord_announcement_webhook_required_groups",
                to="groupmanagement.group",
                verbose_name="Group restrictions",
            ),
        ),
    ]
